#include "higgsinterface001.h"
#include "log.h"

struct HiggsMessage {
    enum { kMessage_QueryInterface = 0xF9279A57 };  // Randomly generated by HIGGS
    void* (*GetApiFunction)(unsigned int revisionNumber) = nullptr;
};

// Stores the API after it has already been fetched
HiggsPluginAPI::IHiggsInterface001* g_higgsInterface = nullptr;

// Fetches the interface to use from HIGGS
HiggsPluginAPI::IHiggsInterface001* HiggsPluginAPI::GetHiggsInterface001(
    const SKSE::MessagingInterface* messagingInterface)
{
    // If the interface has already been fetched, return the same object
    if (g_higgsInterface) {
        return g_higgsInterface;
    }

    if (!messagingInterface) {
        spdlog::error("GetHiggsInterface001: messagingInterface is null");
        return nullptr;
    }

    // Dispatch a message to get the plugin interface from HIGGS
    // CommonLibSSE-NG signature: Dispatch(messageType, data, dataLen, receiver)
    HiggsMessage higgsMessage;
    bool dispatched = messagingInterface->Dispatch(
        HiggsMessage::kMessage_QueryInterface,
        (void*)&higgsMessage,
        sizeof(HiggsMessage*),
        "HIGGS"
    );

    spdlog::info("HIGGS message dispatch result: {}", dispatched);

    if (!higgsMessage.GetApiFunction) {
        spdlog::error("Failed to get HIGGS API function - HIGGS may not be installed or responded");
        return nullptr;
    }

    // Fetch the API for this version of the HIGGS interface
    g_higgsInterface = static_cast<IHiggsInterface001*>(higgsMessage.GetApiFunction(1));

    if (g_higgsInterface) {
        spdlog::info("Successfully obtained HIGGS interface (build {})", g_higgsInterface->GetBuildNumber());
    }

    return g_higgsInterface;
}
